# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: pagaleveDeploy
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  memorySize: 128

plugins:
  - serverless-scriptable-plugin

custom:
  scriptable:
    hooks:
      before:build: npm run build

package:
  exclude:
    - .github/**
    - src/**
    - tests/**
    - nodemon.json
    - README.md

functions:
  app:
    handler: dist/handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    environment:
      DATABASE_URL: mongodb+srv://voltzadmin:m4AKUN03UF6aRu2P@cluster0.f3coa.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
